name: adaptive_navigation_widget
description: A Flutter package to ease the development of an adaptive navigation.
version: 0.0.7
repository: https://github.com/c0pp1ce/adaptive_navigation

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.1.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
